spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: webmaster
    url: jdbc:mariadb://localhost:3306/godtiner_db
    password: '1234'
  jpa:
    properties:
      hibernate:
        show-sql: 'true'
        format_sql: 'true'
    hibernate:
      ddl-auto: update
  profiles:
    include:
      - jwt
      - local
  data:
    web:
      pageable:
        default-page-size: 6  #??? ? ? ???, 6?? ??

  servlet.multipart.max-file-size: 5MB
  servlet.multipart.max-request-size: 5MB

logging:
  level:
    org:
      apache:
        coyote:
          http11: debug
    org.hibernate:
      SQL: debug
      type.descriptor.sql.BasicBinder: trace # 로그 레벨 설정 추가


